import os
import sys
import shutil
from datetime import datetime


# Agent-specific instructions injected AFTER the warning, BEFORE project content.
# These never appear in PROJECT.md — they are generated here.

CLAUDE_AGENT_HEADER = """
## Huong dan rieng cho Claude Code

- File nay AUTO-GENERATED tu PROJECT.md. Khong sua truc tiep.
- Skills co san: Spec Kit (`.claude/skills/speckit-*/`) + UI UX Pro Max (`.claude/skills/ui-ux-pro-max/`)
- PROJECT.md la nguon su that. Neu header nay mau thuan PROJECT.md, follow PROJECT.md.
- Spec Kit la workflow ho tro, chi dung cho feature lon, API/schema/cross-module change, major UI flow, roadmap planning, hoac khi user yeu cau spec/plan/tasks.
- Khong dung Spec Kit mac dinh cho hotfix nho, audit-only, docs-only don gian, protected regression fix, hoac one-file obvious fix.
- UI UX Pro Max chi dung khi task lien quan UI/UX; Robot Bi design rules va frontend hien co override generic skill rules.
- Phan cong: Claude Code xu ly task theo yeu cau user va pham vi repo hien tai
- Doc `.claude/handoff.md` o dau moi session truoc khi lam gi

## Kiem tra moi truong

Neu phat hien bat ky dieu kien sau, AI duoc bao cao va de xuat setup:
- Import `faster_whisper`, `chromadb`, `pygame`, `edge_tts` that bai
- File `.env` khong ton tai hoac thieu bien bat buoc
- Thu muc `.claude/skills/` khong co
- Nguoi dung noi: "may moi", "chua cai", "setup", "fresh install"

Khong tu cai package, download tool, sua `.env`, hoac chay global installer khi chua co approval cua user. Doc "Machine Setup Policy" trong PROJECT.md.

"""

CODEX_AGENT_HEADER = """
## Instructions for Codex CLI

- This file is AUTO-GENERATED from PROJECT.md. Do not edit directly.
- Available skills: Spec Kit (`.agents/skills/speckit-*/`)
- PROJECT.md is the source of truth. If this header conflicts with PROJECT.md, follow PROJECT.md.
- Spec Kit is a supporting workflow. Use it only for large features, API/schema changes, cross-module changes, major UI flows, roadmap planning, or when the user explicitly asks for spec/plan/tasks.
- Do not use Spec Kit by default for small hotfixes, audit-only tasks, simple docs-only edits, protected regression fixes, or one-file obvious fixes.
- Codex CLI handles code, docs, tests, API, data model, business rules, and UI work according to the user's request and the current repo scope.
- Read `.claude/handoff.md` at the start of every session

## Environment Check

If any of the following is detected, report it and propose setup:
- Import of `faster_whisper`, `chromadb`, `pygame`, `edge_tts` fails
- `.env` file missing or required vars not set
- `.agents/skills/` directory missing
- User mentions: "new machine", "fresh install", "not installed", "setup"

Do not install packages, download tools, edit `.env`, or run global installers without user approval. Read "Machine Setup Policy" in PROJECT.md.

"""


def sync_files():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    if not os.path.exists("PROJECT.md"):
        print("[ERROR] Khong tim thay PROJECT.md!")
        return

    with open("PROJECT.md", "r", encoding="utf-8") as f:
        project_content = f.read()

    warning = """WARNING: THIS FILE IS AUTO-GENERATED
WARNING: DO NOT EDIT THIS FILE DIRECTLY
WARNING: Edit PROJECT.md then run: python sync.py
WARNING: Any manual changes will be overwritten
"""

    # CLAUDE.md -- cho Claude Code
    claude_md = warning + CLAUDE_AGENT_HEADER + project_content
    with open("CLAUDE.md", "w", encoding="utf-8") as f:
        f.write(claude_md)

    # AGENTS.md -- cho Codex CLI
    agents_content = project_content
    agents_md = warning + CODEX_AGENT_HEADER + agents_content
    with open("AGENTS.md", "w", encoding="utf-8") as f:
        f.write(agents_md)

    # Mirror skills: .claude/skills/ (ban goc) -> .agents/skills/ (mirror local cho Codex).
    # .agents/ la mirror gitignore -> chi sua skill o .claude/, chay sync.py la Codex tu cap nhat.
    n_skills = mirror_skills()

    print(f"[OK] Da sync thanh cong luc {datetime.now().strftime('%H:%M:%S')}")
    print(" -> CLAUDE.md (cho Claude Code)")
    print(" -> AGENTS.md (cho Codex CLI)")
    if n_skills is not None:
        print(f" -> .agents/skills/ (mirror {n_skills} skill cho Codex)")


def mirror_skills(src=".claude/skills", dst=".agents/skills"):
    """Mirror src -> dst (exact parity, xoa skill thua o dst). Tra ve so skill, hoac None neu bo qua."""
    if not os.path.isdir(src):
        print(f"[WARN] Bo qua mirror skills: khong thay {src}")
        return None
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    return sum(1 for e in os.scandir(dst) if e.is_dir())


if __name__ == "__main__":
    sync_files()
