import os
import sys
from datetime import datetime


def sync_files():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    if not os.path.exists("PROJECT.md"):
        print("[ERROR] Không tìm thấy PROJECT.md!")
        return

    with open("PROJECT.md", "r", encoding="utf-8") as f:
        project_content = f.read()

    # Header cảnh báo chung
    warning = """WARNING: THIS FILE IS AUTO-GENERATED
WARNING: DO NOT EDIT THIS FILE DIRECTLY
WARNING: Edit PROJECT.md then run: python sync.py
WARNING: Any manual changes will be overwritten
"""

    # CLAUDE.md (phiên bản tiếng Việt cho Claude Code)
    claude_md = warning + project_content
    with open("CLAUDE.md", "w", encoding="utf-8") as f:
        f.write(claude_md)

    # AGENTS.md (phiên bản tiếng Anh cho Codex)
    agents_md = warning + project_content.replace("QUY TẮC BẮT BUỘC", "MANDATORY RULES") \
                                         .replace("PROTECTED FIXES", "PROTECTED FIXES") \
                                         .replace("TUYỆT ĐỐI KHÔNG ĐƯỢC PHÁ", "ABSOLUTELY DO NOT BREAK")
    with open("AGENTS.md", "w", encoding="utf-8") as f:
        f.write(agents_md)

    print(f"[OK] Đã sync thành công lúc {datetime.now().strftime('%H:%M:%S')}")
    print(" -> CLAUDE.md (cho Claude Code)")
    print(" -> AGENTS.md (cho Codex CLI)")


if __name__ == "__main__":
    sync_files()
